Update Convert-Kelee.yml

diff --git a/.github/workflows/Convert-Kelee.yml b/.github/workflows/Convert-Kelee.yml
--- a/.github/workflows/Convert-Kelee.yml
+++ b/.github/workflows/Convert-Kelee.yml
@@ -57,8 +57,10 @@ jobs:
             Modules_name=$(echo "$plugin_url" | sed -E 's/\.plugin$//I' | xargs basename)
             echo "Downloading $plugin_url to Modules/Loon/Kelee/Official/${Modules_name}.plugin"
             mkdir -p "Modules/Loon/Kelee/Official" 
-            curl -A "Surge Mac/2985" -L "$plugin_url" -o "Modules/Loon/Kelee/${Modules_name}.plugin" || echo "Failed to download $plugin_url"
             curl -A "Surge Mac/2985" -L "$plugin_url" -o "Modules/Loon/Kelee/Official/${Modules_name}.plugin" || echo "Failed to download $plugin_url"
+
+            echo "Copying ${Modules_name}.plugin to Modules/Loon/Kelee/"
+            cp "Modules/Loon/Kelee/Official/${Modules_name}.plugin" "Modules/Loon/Kelee/${Modules_name}.plugin" || echo "Failed to copy ${Modules_name}.plugin"
           done < Kelee_plugin_urls.txt
           
       - name: Generate plugin URLs
