Update Kelee.yml

diff --git a/.github/workflows/Kelee.yml b/.github/workflows/Kelee.yml
--- a/.github/workflows/Kelee.yml
+++ b/.github/workflows/Kelee.yml
@@ -1,8 +1,6 @@
 name: Extract Kelee plugin
 
 on:
-  push:
-    branches: [ main ]
   schedule:
     - cron: '5,30,55 * * * *'
   workflow_dispatch:
@@ -58,6 +56,32 @@ jobs:
             curl -A "Surge Mac/2985" -L "$plugin_url" -o "Modules/Loon/Kelee/${Modules_name}.plugin" || echo "Failed to download $plugin_url"
           done < Kelee_plugin_urls.txt
 
+
+      - name: Find and replace external JS resources
+        continue-on-error: true  # 确保步骤在部分失败时继续执行
+        run: |
+          js_base_url="https://github.com/ifflagged/Darwin/raw/main/Modules/JS"
+          mkdir -p Modules/JS
+          for plugin_file in Modules/Loon/Kelee/*.plugin; do
+            echo "Processing $plugin_file"
+            # 查找 .js 文件的外部链接
+            js_links=$(grep -oP 'https?://[^ ]+\.js' "$plugin_file" || echo "")
+            for js_link in $js_links; do
+              js_filename=$(basename "$js_link")
+              local_js_path="Modules/JS/Kelee/$js_filename"
+              # 使用指定的 User-Agent 下载 .js 文件
+              echo "Downloading $js_link to $local_js_path"
+              if curl -A "Surge Mac/2985" -L -o "$local_js_path" "$js_link"; then
+                echo "Download successful for $js_link"
+                # 替换 plugin 文件中的链接为 GitHub 仓库的路径
+                github_js_url="$js_base_url/$js_filename"
+                sed -i "s|$js_link|$github_js_url|g" "$plugin_file"
+              else
+                echo "Failed to download $js_link, skipping..."
+              fi
+            done
+          done
+          
       - name: Generate plugin URLs
         run: |
           plugin_base_url="https://github.com/ifflagged/Darwin/raw/main/Modules/Loon/Kelee/"
@@ -86,31 +110,6 @@ jobs:
           curl -A "Surge Mac/2985" -L -o "Modules/Shadowrocket/Kelee/${Modules_name}.sgmodule" "$Shadowrocket_url" || echo "Failed to download ${Modules_name}.sgmodule"
           curl -A "Surge Mac/2985" -L -o "Modules/Shadowrocket/Kelee/Beta/${Modules_name}.sgmodule" "$Shadowrocket_Beta_url" || echo "Failed to download ${Modules_name}.sgmodule"
           done < plugin_local_url.txt
-
-      - name: Find and replace external JS resources
-        continue-on-error: true  # 确保步骤在部分失败时继续执行
-        run: |
-          js_base_url="https://github.com/ifflagged/Darwin/raw/main/Modules/JS"
-          mkdir -p Modules/JS
-          for plugin_file in Modules/Loon/Kelee/*.plugin; do
-            echo "Processing $plugin_file"
-            # 查找 .js 文件的外部链接
-            js_links=$(grep -oP 'https?://[^ ]+\.js' "$plugin_file" || echo "")
-            for js_link in $js_links; do
-              js_filename=$(basename "$js_link")
-              local_js_path="Modules/JS/$js_filename"
-              # 使用指定的 User-Agent 下载 .js 文件
-              echo "Downloading $js_link to $local_js_path"
-              if curl -A "Surge Mac/2985" -L -o "$local_js_path" "$js_link"; then
-                echo "Download successful for $js_link"
-                # 替换 plugin 文件中的链接为 GitHub 仓库的路径
-                github_js_url="$js_base_url/$js_filename"
-                sed -i "s|$js_link|$github_js_url|g" "$plugin_file"
-              else
-                echo "Failed to download $js_link, skipping..."
-              fi
-            done
-          done
 
       - name: Commit and push changes
         env:
